adoptium/api.adoptium.net

- docs/api-planning.md
> Start of adoptium api planning

- docs/api-planning.md
Here's are some initial thoughts to prompt discussion. 
They are based on the context/experience I have so are there to challenged by those more in the know :)
> Contributions to v4 planning docs

- docs/adr/0004-remove-semver.md
> add ADR Remove Semver From the API

- adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/filters/VersionRangeFilter.kt
- adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/info/ReleaseListResource.kt
- adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/stats/DownloadStatsResource.kt
- adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/ReleaseNamesPathTest.kt
Mitigates https://github.com/AdoptOpenJDK/openjdk-api-v3/issues/362
@karianna 
@johnoliver
> Respond 400 on invalid version ranges for release_versions

- docs/adr/0006-update-rework.md
> Add proposed rework of update mechanism

- docs/adr/0005-update-paging.md
> Add ADR to update paging

- docs/adr/0007-update-notification.md
> Add update notification adr

- .gitignore
- CODE_OF_CONDUCTION.md
- adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/pom.xml
- adoptopenjdk-updater-parent/adoptopenjdk-api-v3-updater/pom.xml
- pom.xml
> Merge in from adoptopenjdk

- adoptopenjdk-api-v3-persistence/src/main/kotlin/net/adoptopenjdk/api/v3/DownloadStatsInterface.kt
- adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/stats/DownloadStatsResource.kt
- adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/MonthlyStatsPathTest.kt
- adoptopenjdk-models-parent/adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/config/APIConfig.kt
> Fix monthly stats being incorrectly calculated when calculated over multiple years

- adoptopenjdk-api-v3-persistence/src/main/kotlin/net/adoptopenjdk/api/v3/DownloadStatsInterface.kt
> Remove time from monthly stats grouping

- adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/pom.xml
- pom.xml
> Bump versions

- adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/filters/VersionRangeFilter.kt
- adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/VersionRangeFilterTest.kt
- adoptopenjdk-models-parent/adoptopenjdk-api-v3-models/src/test/kotlin/api/VersionParserTest.kt
- adoptopenjdk-updater-parent/adoptopenjdk-datasources-parent/adoptopenjdk-github-datasource/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/github/graphql/clients/GraphQLGitHubReleaseRequest.kt
> Fix version range filter unexpectedly including pre-release versions

- adoptopenjdk-updater-parent/adoptopenjdk-datasources-parent/adoptopenjdk-github-datasource/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/github/graphql/clients/GraphQLGitHubInterface.kt
> Fix server timeout from graphql

- adoptopenjdk-updater-parent/adoptopenjdk-mappers-parent/adopt-mappers/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/adopt/AdoptReleaseMapper.kt
> exclude the release jdk-2021-01-13-07-01

- .s2i/bin/assemble
- scripts/frontendHealthCheck.sh
> Add frontend health checks

- adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/filters/ReleaseFilter.kt
> Fix vendor filter not showing semeru builds

- adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/OpenApiDocs.kt
* HTML is not supported.
* fixes #124.
> [#124] use CommonMark for description fields

- adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/filters/ReleaseFilter.kt
- adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsResourceFeatureReleasePathTest.kt
- adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsResourceVersionPathTest.kt
- adoptopenjdk-models-parent/adoptopenjdk-api-v3-adopt-specific-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/AdoptVendor.kt
- adoptopenjdk-models-parent/adoptopenjdk-api-v3-adopt-specific-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/VendorSchemaRef.kt
- adoptopenjdk-models-parent/adoptopenjdk-api-v3-adoptium-specific-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/AdoptiumVendor.kt
- adoptopenjdk-models-parent/adoptopenjdk-api-v3-adoptium-specific-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/VendorSchemaRef.kt
- adoptopenjdk-models-parent/adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/Vendor.kt
- adoptopenjdk-updater-parent/adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/AdoptRepository.kt
- adoptopenjdk-updater-parent/adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptReposTestDataGenerator.kt
- adoptopenjdk-updater-parent/adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/SemeruMapperTest.kt
- adoptopenjdk-updater-parent/adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/SemeruReleaseMapperTest.kt
> rename adoptium vendor to eclipse

- deploy/Dockerfile
> Add docker build

- .github/workflows/build.yml
- pom.xml
> version bumps

- adoptopenjdk-updater-parent/adoptopenjdk-api-v3-updater/src/test/resources/example-release.json
- adoptopenjdk-updater-parent/adoptopenjdk-mappers-parent/adopt-mappers/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/adopt/AdoptReleaseMapper.kt
> Prevent json metadata being incorrectly being classified as a binary

- adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/main/resources/application.properties
- pom.xml
> Bump quarkus. Re-enable compression. Fix CORS

- adoptopenjdk-models-parent/adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/Versions.kt
> add 17 to lts list

- adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/SwaggerUiRoute.kt
- adoptopenjdk-models-parent/adoptopenjdk-api-v3-adopt-specific-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/VendorSchemaRef.kt
Redirect requests to `/swagger-ui` to `/q/swagger-ui`
> Fix swagger redirect #177

- adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/SwaggerUiRoute.kt
> add openapi to redirect list

- adoptopenjdk-updater-parent/adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/stats/StatsInterface.kt
- adoptopenjdk-updater-parent/adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/stats/dockerstats/DockerStatsInterface.kt
- adoptopenjdk-updater-parent/adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/stats/dockerstats/DockerStatsInterfaceAdoptOpenJdk.kt
- adoptopenjdk-updater-parent/adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/stats/dockerstats/DockerStatsInterfaceAdoptium.kt
- adoptopenjdk-updater-parent/adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/DockerStatsInterfaceTest.kt
- adoptopenjdk-updater-parent/adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/StatsCalculatorTest.kt
> Update docker stats to pull correct adoptopenjdk/adoptium stats

- scripts/frontendHealthCheck.sh
> Remove redundant restart code

- adoptopenjdk-api-v3-persistence/src/main/kotlin/net/adoptopenjdk/api/v3/DownloadStatsInterface.kt
> remove versions from stats with 0 downloads

- adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/OpenApiDocs.kt
- adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/filters/BinaryFilter.kt
- adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/AssetsResource.kt
- adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/ReleaseEndpoint.kt
- adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/SwaggerUiRoute.kt
- adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/info/ReleaseListResource.kt
- adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/packages/BinaryResource.kt
- adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/packages/InstallerResource.kt
- adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/packages/PackageEndpoint.kt
- adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/stats/DownloadStatsResource.kt
- adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsPathTest.kt
- adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsResourceFeatureReleasePathSortOrderTest.kt
- adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsResourceReleaseNamePathTest.kt
- adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/FrontendTest.kt
- adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/packages/BinaryPathTest.kt
- adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/packages/InstallerPathTest.kt
- adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/packages/PackageEndpointTest.kt
- adoptopenjdk-models-parent/adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/config/Ecosystem.kt
- adoptopenjdk-models-parent/adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/Binary.kt
- adoptopenjdk-models-parent/adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/CLib.kt
- adoptopenjdk-updater-parent/adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/APIDataStoreTest.kt
- adoptopenjdk-updater-parent/adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptBinaryMapperTest.kt
- adoptopenjdk-updater-parent/adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptReposTest.kt
- adoptopenjdk-updater-parent/adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptReposTestDataGenerator.kt
- adoptopenjdk-updater-parent/adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/StatsCalculatorTest.kt
- adoptopenjdk-updater-parent/adoptopenjdk-mappers-parent/adopt-mappers/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/adopt/AdoptBinaryMapper.kt
- adoptopenjdk-updater-parent/adoptopenjdk-mappers-parent/mappers-common/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/BinaryMapper.kt
- adoptopenjdk-updater-parent/adoptopenjdk-mappers-parent/upstream-mappers/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/upstream/UpstreamBinaryMapper.kt
> Add detection of static images and clib type. Fixes #186 and #191

- CONTRIBUTING.md
> AdoptOpenJDK -> Adoptium rename in CONTRIBUTING.md

- adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/packages/BinaryPathTest.kt
- adoptopenjdk-updater-parent/adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/AdoptReposBuilder.kt
- adoptopenjdk-updater-parent/adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptBinaryMapperTest.kt
- adoptopenjdk-updater-parent/adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/UpdateRunner.kt
- adoptopenjdk-updater-parent/adoptopenjdk-mappers-parent/adopt-mappers/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/adopt/AdoptBinaryMapper.kt
- deploy/run.sh
- pom.xml
> Account for adoptium producing incorrect metadata for staticlibs

- adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/pom.xml
- adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/main/resources/application.properties
- adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/main/resources/logback.xml
- adoptopenjdk-updater-parent/adoptopenjdk-api-v3-updater/pom.xml
- adoptopenjdk-updater-parent/adoptopenjdk-api-v3-updater/src/main/resources/application.properties
- pom.xml
> Move quarkus logging to logback

- adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/main/resources/application.properties
- adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/main/resources/logback.xml
> Dial back over logging

- adoptium-frontend-parent/adoptium-api-v3-frontend/src/main/kotlin/net/adoptium/api/v3/routes/packages/BinaryResource.kt
> Allow null user agent

- adoptium-api-v3-persistence/src/main/kotlin/net/adoptium/api/v3/dataSources/persitence/ApiPersistence.kt
- adoptium-api-v3-persistence/src/main/kotlin/net/adoptium/api/v3/dataSources/persitence/mongo/MongoApiPersistence.kt
- adoptium-models-parent/adoptium-api-v3-models/src/main/kotlin/net/adoptium/api/v3/dataSources/models/Releases.kt
- adoptium-models-parent/adoptium-api-v3-models/src/main/kotlin/net/adoptium/api/v3/models/GHReleaseMetadata.kt
- adoptium-updater-parent/adoptium-api-v3-updater/src/main/kotlin/net/adoptium/api/v3/AdoptReposBuilder.kt
- adoptium-updater-parent/adoptium-api-v3-updater/src/main/kotlin/net/adoptium/api/v3/V3Updater.kt
- adoptium-updater-parent/adoptium-api-v3-updater/src/test/kotlin/net/adoptium/api/AdoptReleaseMapperTest.kt
- adoptium-updater-parent/adoptium-api-v3-updater/src/test/kotlin/net/adoptium/api/AdoptReposBuilderTest.kt
- adoptium-updater-parent/adoptium-api-v3-updater/src/test/kotlin/net/adoptium/api/GHSummaryTestDataGenerator.kt
- adoptium-updater-parent/adoptium-api-v3-updater/src/test/kotlin/net/adoptium/api/GraphQLGitHubReleaseClientTest.kt
- adoptium-updater-parent/adoptium-api-v3-updater/src/test/kotlin/net/adoptium/api/MongoAPIPersistenceTests.kt
- adoptium-updater-parent/adoptium-api-v3-updater/src/test/kotlin/net/adoptium/api/SemeruReleaseMapperTest.kt
- adoptium-updater-parent/adoptium-api-v3-updater/src/test/kotlin/net/adoptium/api/UpstreamReleaseMapperTest.kt
- adoptium-updater-parent/adoptium-api-v3-updater/src/test/kotlin/net/adoptium/api/testDoubles/InMemoryApiPersistence.kt
- adoptium-updater-parent/adoptium-datasources-parent/adoptium-github-datasource/src/main/kotlin/net/adoptium/api/v3/dataSources/github/graphql/clients/GraphQLGitHubReleaseRequest.kt
- adoptium-updater-parent/adoptium-datasources-parent/adoptium-github-datasource/src/main/kotlin/net/adoptium/api/v3/dataSources/github/graphql/clients/GraphQLGitHubRepositoryClient.kt
- adoptium-updater-parent/adoptium-datasources-parent/adoptium-github-datasource/src/main/kotlin/net/adoptium/api/v3/dataSources/github/graphql/clients/GraphQLGitHubSummaryClient.kt
- adoptium-updater-parent/adoptium-datasources-parent/adoptium-github-datasource/src/main/kotlin/net/adoptium/api/v3/dataSources/github/graphql/models/GHAssets.kt
- adoptium-updater-parent/adoptium-datasources-parent/adoptium-github-datasource/src/main/kotlin/net/adoptium/api/v3/dataSources/github/graphql/models/GHRelease.kt
- adoptium-updater-parent/adoptium-datasources-parent/adoptium-github-datasource/src/main/kotlin/net/adoptium/api/v3/dataSources/github/graphql/models/summary/GHReleaseSummary.kt
> When performing incremental update, use binary count to detect changes

- .github/workflows/ci.yml
- .s2i/bin/assemble
- CONTRIBUTING.md
- adoptium-api-v3-persistence/pom.xml
- adoptium-api-v3-telemetry/pom.xml
- adoptium-frontend-parent/adoptium-api-v3-frontend/pom.xml
- adoptium-frontend-parent/adoptium-frontend-assets/pom.xml
- adoptium-frontend-parent/adoptopenjdk-frontend-assets/pom.xml
- adoptium-frontend-parent/pom.xml
- adoptium-models-parent/adoptium-api-v3-adopt-specific-models/pom.xml
- adoptium-models-parent/adoptium-api-v3-adopt-specific-models/src/main/kotlin/net/adoptium/api/v3/models/AdoptJvmImpl.kt
- adoptium-models-parent/adoptium-api-v3-adopt-specific-models/src/main/kotlin/net/adoptium/api/v3/models/AdoptVendor.kt
- adoptium-models-parent/adoptium-api-v3-adoptium-specific-models/pom.xml
- adoptium-models-parent/adoptium-api-v3-adoptium-specific-models/src/main/kotlin/net/adoptium/api/v3/models/AdoptiumJvmImpl.kt
- adoptium-models-parent/adoptium-api-v3-adoptium-specific-models/src/main/kotlin/net/adoptium/api/v3/models/AdoptiumVendor.kt
- adoptium-models-parent/adoptium-api-v3-models/pom.xml
- adoptium-models-parent/pom.xml
- adoptium-updater-parent/adoptium-api-v3-updater/pom.xml
- adoptium-updater-parent/adoptium-datasources-parent/adoptium-github-datasource/pom.xml
- adoptium-updater-parent/adoptium-datasources-parent/adoptium-http-client-datasource/pom.xml
- adoptium-updater-parent/adoptium-datasources-parent/pom.xml
- adoptium-updater-parent/adoptium-mappers-parent/adopt-mappers/pom.xml
- adoptium-updater-parent/adoptium-mappers-parent/mappers-common/pom.xml
- adoptium-updater-parent/adoptium-mappers-parent/pom.xml
- adoptium-updater-parent/adoptium-mappers-parent/upstream-mappers/pom.xml
- adoptium-updater-parent/pom.xml
- deploy/Dockerfile
- docs/STRUCTURE.md
- pom.xml
> Rework switching between adoptopenjdk and adoptium builds

- .github/workflows/build-docker.yml
> Restart updater as well as frontend

- adoptium-models-parent/adoptium-api-v3-models/src/main/kotlin/net/adoptium/api/v3/models/Versions.kt
> Bump to java 19

- deploy/Dockerfile
> update docker deploy to 17

- .github/workflows/build-docker.yml
> Attempt to fix Azure login issue

- .github/workflows/build-docker.yml
> Fix whitespace

- adoptium-updater-parent/adoptium-mappers-parent/adopt-mappers/src/main/kotlin/net/adoptium/api/v3/mapping/adopt/AdoptBinaryMapper.kt
> Support build metadata containing a variant of 'temurin'

- .mvn/wrapper/maven-wrapper.properties
- pom.xml
> Move maven to 3.8.5

- adoptium-frontend-parent/adoptium-api-v3-frontend/src/main/kotlin/net/adoptium/api/v3/routes/AssetsResource.kt
- adoptium-frontend-parent/adoptium-api-v3-frontend/src/test/kotlin/net/adoptium/api/LatestAssetsPathTest.kt
> add ImageType, Arch and OS to latest filters

- .github/workflows/build-docker.yml
- .mvn/wrapper/maven-wrapper.properties
- CONTRIBUTING.md
- adoptium-frontend-parent/adoptium-api-v3-frontend/src/main/kotlin/net/adoptium/api/v3/routes/AssetsResource.kt
- adoptium-frontend-parent/adoptium-api-v3-frontend/src/test/kotlin/net/adoptium/api/LatestAssetsPathTest.kt
- pom.xml
> Reapply reverted commits

- marketplace/README.md
> add example repo validation

- marketplace/adoptium-marketplace-client/src/main/java/net/adoptium/marketplace/client/MarketplaceClient.java
- marketplace/adoptium-marketplace-client/src/main/java/net/adoptium/marketplace/client/MarketplaceHttpClient.java
- marketplace/adoptium-marketplace-client/src/main/java/net/adoptium/marketplace/client/signature/Rsa256SignatureVerify.java
- marketplace/adoptium-marketplace-client/src/main/java/net/adoptium/marketplace/client/signature/SigRsa256Verifier.java
- marketplace/adoptium-marketplace-client/src/main/java/net/adoptium/marketplace/client/signature/SignatureType.java
- marketplace/adoptium-marketplace-client/src/main/java/net/adoptium/marketplace/client/signature/SignatureVerifier.java
- marketplace/adoptium-marketplace-server/adoptium-marketplace-updater-parent/adoptium-marketplace-updater/src/main/kotlin/net/adoptium/marketplace/server/updater/AdoptiumMarketplaceUpdater.kt
- marketplace/adoptium-marketplace-server/adoptium-marketplace-updater-parent/adoptium-marketplace-updater/src/main/kotlin/net/adoptium/marketplace/server/updater/VendorInfo.kt
- marketplace/adoptium-marketplace-server/adoptium-repo/src/main/kotlin/net/adoptium/marketplace/repo/SignAssets.kt
- marketplace/adoptium-marketplace-utils/src/test/kotlin/SignTestAssets.kt
> Support non-base64 encoded signatures

- marketplace/adoptium-marketplace-utils/src/test/kotlin/ExtractAdoptiumReleases.kt
> Tidy up adoptium repo generation

- marketplace/README.md
- marketplace/adoptium-marketplace-client/src/test/java/net/adoptium/marketplace/client/RepoTest.java
> Add repo validation test class

- marketplace/adoptium-marketplace-utils/src/test/kotlin/ExtractAdoptiumReleases.kt
> Pretty print json

- marketplace/adoptium-marketplace-utils/src/test/kotlin/ExtractAdoptiumReleases.kt
> Filter only jdk and jres

- .github/workflows/build-marketplace.yml
> Use Temurin builds in workflow

- marketplace/adoptium-marketplace-schema/src/main/java/net/adoptium/marketplace/schema/Distribution.java
- marketplace/adoptium-marketplace-schema/src/main/java/net/adoptium/marketplace/schema/Vendor.java
> add bisheng

- marketplace/adoptium-marketplace-schema/src/main/java/net/adoptium/marketplace/schema/Distribution.java
> Add redhat Distribution

- .github/workflows/run-vendor-validation.yml
- marketplace/adoptium-marketplace-client/src/main/java/net/adoptium/marketplace/client/MarketplaceHttpClient.java
- marketplace/adoptium-marketplace-server/adoptium-marketplace-updater-parent/adoptium-marketplace-updater/src/main/kotlin/net/adoptium/marketplace/server/updater/AdoptiumMarketplaceUpdater.kt
- marketplace/adoptium-marketplace-vendor-validation/pom.xml
- marketplace/adoptium-marketplace-vendor-validation/src/test/java/net/adoptium/marketplace/validation/RepoValidationTest.java
- marketplace/adoptium-marketplace-vendor-validation/src/test/java/net/adoptium/marketplace/validation/ValidateRedhatTest.java
- marketplace/pom.xml
> Add data validation test

- marketplace/adoptium-marketplace-schema/src/main/java/net/adoptium/marketplace/schema/OpenjdkVersionData.java
- marketplace/adoptium-marketplace-schema/src/main/java/net/adoptium/marketplace/schema/Release.java
- marketplace/adoptium-marketplace-server/adoptium-marketplace-persistence/src/main/kotlin/net/adoptium/marketplace/dataSources/persitence/mongo/MongoVendorPersistence.kt
- marketplace/adoptium-marketplace-vendor-validation/src/test/java/net/adoptium/marketplace/validation/RepoValidationTest.java
> Assert that release name, link and version are unique

- marketplace/adoptium-marketplace-client/src/main/java/net/adoptium/marketplace/client/MarketplaceHttpClient.java
- marketplace/adoptium-marketplace-client/src/main/java/net/adoptium/marketplace/client/signature/FailedToValidateSignatureException.java
> Log error message

- marketplace/adoptium-marketplace-client/src/main/java/net/adoptium/marketplace/client/MarketplaceClient.java
- marketplace/adoptium-marketplace-client/src/test/java/net/adoptium/marketplace/client/Rsa256VerifierTest.java
- marketplace/adoptium-marketplace-schema/src/main/java/net/adoptium/marketplace/schema/ReleaseUpdateInfo.java
- marketplace/adoptium-marketplace-server/adoptium-marketplace-updater-parent/adoptium-marketplace-updater/src/main/kotlin/net/adoptium/marketplace/server/updater/AdoptiumMarketplaceUpdater.kt
- marketplace/adoptium-marketplace-server/adoptium-marketplace-updater-parent/adoptium-marketplace-updater/src/main/kotlin/net/adoptium/marketplace/server/updater/routes/UpdateTrigger.kt
> Make any update failure abort the whole update for that vendor

- marketplace/adoptium-marketplace-utils/src/test/kotlin/ExtractAdoptiumReleases.kt
- marketplace/adoptium-marketplace-utils/src/test/kotlin/ExtractIbmReleases.kt
- marketplace/adoptium-marketplace-utils/src/test/kotlin/ExtractReleases.kt
> Add ibm extractor

- marketplace/adoptium-marketplace-utils/src/test/kotlin/ExtractAdoptiumReleases.kt
> Filter out releases after, 8u322-b06, 11.0.14.1+1, 17.0.2+8

- marketplace/adoptium-marketplace-utils/src/test/kotlin/ExtractIbmReleases.kt
> Pull IBM ce only

- adoptium-updater-parent/adoptium-api-v3-updater/src/test/kotlin/net/adoptium/api/AdoptReleaseMapperTest.kt
- adoptium-updater-parent/adoptium-mappers-parent/adopt-mappers/src/main/kotlin/net/adoptium/api/v3/mapping/adopt/AdoptBinaryMapper.kt
- adoptium-updater-parent/adoptium-mappers-parent/adopt-mappers/src/main/kotlin/net/adoptium/api/v3/mapping/adopt/AdoptReleaseMapper.kt
> Exclude sbom binaries

- adoptium-updater-parent/adoptium-api-v3-updater/src/test/kotlin/net/adoptium/api/AdoptReleaseMapperTest.kt
- adoptium-updater-parent/adoptium-mappers-parent/adopt-mappers/src/main/kotlin/net/adoptium/api/v3/mapping/adopt/AdoptBinaryMapper.kt
- adoptium-updater-parent/adoptium-mappers-parent/adopt-mappers/src/main/kotlin/net/adoptium/api/v3/mapping/adopt/AdoptReleaseMapper.kt
Reverts adoptium/api.adoptium.net#439
> Revert "Exclude sbom binaries"

- adoptium-updater-parent/adoptium-api-v3-updater/src/main/kotlin/net/adoptium/api/v3/AdoptRepository.kt
> add exclusion to adoptium mapper

- adoptium-frontend-parent/adoptium-api-v3-frontend/src/main/kotlin/net/adoptium/api/v3/routes/AssetsResource.kt
- adoptium-models-parent/adoptium-api-v3-models/src/main/kotlin/net/adoptium/api/v3/models/BinaryAssetView.kt
closes: https://github.com/adoptium/api.adoptium.net/issues/316
> Add release_link to latest route. Fixes #316

- .github/workflows/ci.yml
- .github/workflows/publish.yml
> add maven cache to setup-java

- .github/workflows/build-marketplace.yml
> Add cache to marketplace CI job

- adoptium-updater-parent/adoptium-api-v3-updater/src/test/kotlin/net/adoptium/api/AdoptBinaryMapperTest.kt
- adoptium-updater-parent/adoptium-api-v3-updater/src/test/kotlin/net/adoptium/api/UpstreamBinaryMapperTest.kt
- adoptium-updater-parent/adoptium-mappers-parent/adopt-mappers/src/main/kotlin/net/adoptium/api/v3/mapping/adopt/AdoptBinaryMapper.kt
- adoptium-updater-parent/adoptium-mappers-parent/upstream-mappers/src/main/kotlin/net/adoptium/api/v3/mapping/upstream/UpstreamBinaryMapper.kt
> fix: add sbom*.json into binary assets list

- adoptium-models-parent/adoptium-api-v3-models/src/main/kotlin/net/adoptium/api/v3/models/Architecture.kt
> Alias x86_64 to x64 for front end queries. Fixes #468

- adoptium-models-parent/adoptium-api-v3-models/src/main/kotlin/net/adoptium/api/v3/models/FileNameMatcher.kt
- adoptium-models-parent/adoptium-api-v3-models/src/main/kotlin/net/adoptium/api/v3/models/ImageType.kt
- adoptium-updater-parent/adoptium-api-v3-updater/src/test/kotlin/net/adoptium/api/AdoptBinaryMapperTest.kt
- adoptium-updater-parent/adoptium-api-v3-updater/src/test/kotlin/net/adoptium/api/AdoptReleaseMapperTest.kt
- adoptium-updater-parent/adoptium-mappers-parent/adopt-mappers/src/main/kotlin/net/adoptium/api/v3/mapping/adopt/AdoptReleaseMapper.kt
> add sbom and gpg-key tests

- pom.xml
> Remove unused repo

- adoptium-frontend-parent/adoptium-api-v3-frontend/src/main/kotlin/net/adoptium/api/v3/Pagination.kt
- adoptium-frontend-parent/adoptium-api-v3-frontend/src/main/kotlin/net/adoptium/api/v3/routes/AssetsResource.kt
- adoptium-frontend-parent/adoptium-api-v3-frontend/src/main/kotlin/net/adoptium/api/v3/routes/info/ReleaseListResource.kt
- adoptium-frontend-parent/adoptium-api-v3-frontend/src/main/kotlin/net/adoptium/api/v3/routes/packages/BinaryResource.kt
- adoptium-frontend-parent/adoptium-api-v3-frontend/src/test/kotlin/net/adoptium/api/AssetsResourceFeatureReleasePathSortOrderTest.kt
- adoptium-frontend-parent/adoptium-api-v3-frontend/src/test/kotlin/net/adoptium/api/ReleaseNamesPathTest.kt
> Use links header for next page pagination

- adoptium-api-v3-telemetry/pom.xml
- adoptium-models-parent/adoptium-api-v3-models/pom.xml
- adoptium-updater-parent/adoptium-datasources-parent/adoptium-http-client-datasource/pom.xml
- pom.xml
> Add dependencies to top level pom to allow unification with marketplace

- marketplace/adoptium-marketplace-vendor-validation/src/test/java/net/adoptium/marketplace/validation/RepoValidationTest.java
> Add debug info to the key collision failure case

- adoptium-updater-parent/adoptium-mappers-parent/adopt-mappers/src/main/kotlin/net/adoptium/api/v3/mapping/adopt/AdoptReleaseMapper.kt
> Fix repo matching to identify temurin repos. Fixes #488

- adoptium-frontend-parent/adoptium-frontend-assets/src/main/resources/META-INF/resources/css/style.css
- adoptium-frontend-parent/adoptium-frontend-assets/src/main/resources/META-INF/resources/index.html
Signed-off-by: sakshi1215 <sakshi.patle121@gmail.com>
> feat: improve the API landing page

- adoptium-frontend-parent/adoptium-api-v3-frontend/src/main/kotlin/net/adoptium/api/v3/JsonSerialiserConfig.kt
- adoptium-frontend-parent/adoptium-api-v3-frontend/src/main/kotlin/net/adoptium/api/v3/Pagination.kt
- adoptium-frontend-parent/adoptium-api-v3-frontend/src/main/kotlin/net/adoptium/api/v3/routes/AssetsResource.kt
- adoptium-frontend-parent/adoptium-api-v3-frontend/src/main/kotlin/net/adoptium/api/v3/routes/info/ReleaseListResource.kt
- adoptium-frontend-parent/adoptium-api-v3-frontend/src/main/resources/application.properties
- adoptium-frontend-parent/adoptium-api-v3-frontend/src/test/kotlin/net/adoptium/api/AssetsResourceFeatureReleasePathSortOrderTest.kt
- pom.xml
> Add ability to show page count in pagination

- .github/workflows/build-docker.yml
> switch Azure login to use OIDC

- adoptium-frontend-parent/adoptium-api-v3-frontend/src/main/resources/logback.xml
* Allow adding page count to headers. Bump dependencies
* Change to PageCount
* Remove unnecessary code
* Reduce logging of pagination
> Reduce logging of pagination (#509)

- adoptium-api-v3-telemetry/src/main/resources/applicationinsights.json
- adoptium-frontend-parent/adoptium-api-v3-frontend/pom.xml
- adoptium-updater-parent/adoptium-api-v3-updater/pom.xml
- pom.xml
> Merge version upgrades

- .github/workflows/build-docker.yml
- .github/workflows/ci.yml
- .github/workflows/publish.yml
- Fix GitHub action dependencies to specific hash values
- Be explicit about permissions required in actions
- Refine concurrency of CI action
Part of https://github.com/adoptium/adoptium/issues/187
> Fix dependency action hashes and restrict permissions

- .github/workflows/ci.yml
- .github/workflows/publish.yml
Reverts adoptium/api.adoptium.net#522
> Revert "build(deps): bump actions/setup-java from 3.6.0 to 3.7.0"

- README.md
> Link to cookbook

- adoptium-api-v3-persistence/src/main/kotlin/net/adoptium/api/v3/dataSources/persitence/ApiPersistence.kt
- adoptium-api-v3-persistence/src/main/kotlin/net/adoptium/api/v3/dataSources/persitence/mongo/MongoApiPersistence.kt
- adoptium-api-v3-telemetry/src/main/resources/applicationinsights.json
- adoptium-frontend-parent/adoptium-api-v3-frontend/src/main/kotlin/net/adoptium/api/v3/Startup.kt
- adoptium-frontend-parent/adoptium-api-v3-frontend/src/main/kotlin/net/adoptium/api/v3/metrics/OtelInterceptor.kt
- adoptium-frontend-parent/adoptium-api-v3-frontend/src/main/kotlin/net/adoptium/api/v3/routes/info/AvailableReleasesResource.kt
- adoptium-frontend-parent/adoptium-api-v3-frontend/src/main/kotlin/net/adoptium/api/v3/routes/info/ReleaseNotesResource.kt
- adoptium-models-parent/adoptium-api-v3-models/src/main/kotlin/net/adoptium/api/v3/dataSources/models/GitHubId.kt
- adoptium-models-parent/adoptium-api-v3-models/src/main/kotlin/net/adoptium/api/v3/dataSources/models/ReleaseNotes.kt
- adoptium-models-parent/adoptium-api-v3-models/src/main/kotlin/net/adoptium/api/v3/models/Release.kt
- adoptium-models-parent/adoptium-api-v3-models/src/main/kotlin/net/adoptium/api/v3/models/SourcePackage.kt
- adoptium-updater-parent/adoptium-api-v3-updater/src/main/kotlin/net/adoptium/api/v3/AdoptRepository.kt
- adoptium-updater-parent/adoptium-api-v3-updater/src/main/kotlin/net/adoptium/api/v3/V3Updater.kt
- adoptium-updater-parent/adoptium-api-v3-updater/src/main/kotlin/net/adoptium/api/v3/releaseNotes/AdoptReleaseNotes.kt
- adoptium-updater-parent/adoptium-api-v3-updater/src/test/kotlin/net/adoptium/api/AdoptReleaseNotesTest.kt
- adoptium-updater-parent/adoptium-api-v3-updater/src/test/kotlin/net/adoptium/api/AdoptReposTest.kt
- adoptium-updater-parent/adoptium-api-v3-updater/src/test/kotlin/net/adoptium/api/testDoubles/AdoptRepositoryStub.kt
- adoptium-updater-parent/adoptium-api-v3-updater/src/test/kotlin/net/adoptium/api/testDoubles/InMemoryApiPersistence.kt
- adoptium-updater-parent/adoptium-datasources-parent/adoptium-github-datasource/src/main/kotlin/net/adoptium/api/v3/dataSources/github/graphql/clients/GraphQLGitHubInterface.kt
- adoptium-updater-parent/adoptium-datasources-parent/adoptium-github-datasource/src/main/kotlin/net/adoptium/api/v3/dataSources/github/graphql/clients/GraphQLGitHubReleaseClient.kt
- adoptium-updater-parent/adoptium-mappers-parent/adopt-mappers/src/main/kotlin/net/adoptium/api/v3/mapping/adopt/AdoptReleaseMapper.kt
- adoptium-updater-parent/adoptium-mappers-parent/upstream-mappers/src/main/kotlin/net/adoptium/api/v3/mapping/upstream/UpstreamReleaseMapper.kt
- pom.xml
> Add release notes endpoint

- adoptium-models-parent/adoptium-api-v3-models/src/main/kotlin/net/adoptium/api/v3/models/SourcePackage.kt
> Fix class cast exception from SourcePackage

- adoptium-frontend-parent/adoptium-api-v3-frontend/src/main/resources/application.properties
> add headers

- .github/workflows/build-docker.yml
- .github/workflows/ci.yml
- .github/workflows/publish.yml
- adoptium-frontend-parent/adoptium-api-v3-frontend/src/main/resources/application.properties
- pom.xml
> Merge main into marketplace

- .github/workflows/build-docker.yml
- .github/workflows/ci.yml
- .github/workflows/publish.yml
- adoptium-frontend-parent/adoptium-api-v3-frontend/src/main/resources/application.properties
- pom.xml
> Merge main to prod

- README.md
- adoptium-models-parent/adoptium-api-v3-models/src/main/kotlin/net/adoptium/api/v3/models/Versions.kt
> Bump version to 21

- adoptium-models-parent/adoptium-api-v3-models/src/main/kotlin/net/adoptium/api/v3/models/Release.kt
- adoptium-updater-parent/adoptium-mappers-parent/adopt-mappers/src/main/kotlin/net/adoptium/api/v3/mapping/adopt/AdoptReleaseMapper.kt
> Add aqavit tap files

- adoptium-frontend-parent/adoptium-api-v3-frontend/src/main/kotlin/net/adoptium/api/v3/filters/VersionRangeFilter.kt
- adoptium-frontend-parent/adoptium-api-v3-frontend/src/main/kotlin/net/adoptium/api/v3/routes/AssetsResource.kt
- adoptium-frontend-parent/adoptium-api-v3-frontend/src/main/kotlin/net/adoptium/api/v3/routes/ReleaseEndpoint.kt
- adoptium-frontend-parent/adoptium-api-v3-frontend/src/main/kotlin/net/adoptium/api/v3/routes/info/ReleaseListResource.kt
- adoptium-frontend-parent/adoptium-api-v3-frontend/src/test/kotlin/net/adoptium/api/AssetsResourceFeatureReleasePathTest.kt
- adoptium-frontend-parent/adoptium-api-v3-frontend/src/test/kotlin/net/adoptium/api/AssetsResourceVersionPathTest.kt
- adoptium-frontend-parent/adoptium-api-v3-frontend/src/test/kotlin/net/adoptium/api/VersionRangeFilterTest.kt
- adoptium-models-parent/adoptium-api-v3-models/src/main/kotlin/net/adoptium/api/v3/parser/VersionParser.kt
- adoptium-models-parent/adoptium-api-v3-models/src/main/kotlin/net/adoptium/api/v3/parser/maven/SemverParser.kt
- adoptium-models-parent/adoptium-api-v3-models/src/main/kotlin/net/adoptium/api/v3/parser/maven/VersionRange.kt
- adoptium-models-parent/adoptium-api-v3-models/src/test/kotlin/api/SemverParserTest.kt
- adoptium-models-parent/adoptium-api-v3-models/src/test/kotlin/api/VersionRangeTest.kt
- adoptium-updater-parent/adoptium-api-v3-updater/src/test/kotlin/net/adoptium/api/AdoptReposTestDataGenerator.kt
- adoptium-updater-parent/adoptium-api-v3-updater/src/test/kotlin/net/adoptium/api/ReleaseVersionResolverTest.kt
> Allow option for using semver versions as parameters

- .mvn/wrapper/maven-wrapper.properties
- CONTRIBUTING.md
- adoptium-api-versions/pom.xml
- adoptium-updater-parent/adoptium-api-v3-updater/pom.xml
- pom.xml
- ./mvnw clean install -Padoptium and -Padoptopenjdk pass
- Update docs
> update deps 08 june 2023

- adoptium-api-versions/pom.xml
- adoptium-updater-parent/adoptium-api-v3-updater/src/test/kotlin/net/adoptium/api/MongoTest.kt
> Fix failing docker build

- adoptium-api-v3-persistence/src/main/kotlin/net/adoptium/api/v3/DownloadStatsInterface.kt
> fix broken days logic in stats

- adoptium-api-v3-telemetry/pom.xml
- adoptium-api-versions/pom.xml
> Fix missing opentelemetry dependencies

- adoptium-api-v3-telemetry/pom.xml
- adoptium-api-versions/pom.xml
- adoptium-updater-parent/adoptium-datasources-parent/adoptium-github-datasource/src/main/kotlin/net/adoptium/api/v3/dataSources/github/graphql/clients/GraphQLGitHubInterface.kt
- pom.xml
> Bump maven versions

- adoptium-frontend-parent/adoptium-api-v3-frontend/src/main/resources/application.properties
- deploy/run.sh
> Fix deprecated settings

- adoptium-updater-parent/adoptium-api-v3-updater/pom.xml
> add missing dependency

- adoptium-updater-parent/adoptium-api-v3-updater/pom.xml
- adoptium-updater-parent/adoptium-api-v3-updater/src/main/kotlin/net/adoptium/api/v3/Main.kt
- adoptium-updater-parent/adoptium-api-v3-updater/src/main/kotlin/net/adoptium/api/v3/V3Updater.kt
- adoptium-updater-parent/adoptium-datasources-parent/adoptium-github-datasource/src/main/kotlin/net/adoptium/api/v3/dataSources/github/graphql/clients/GraphQLGitHubInterface.kt
> Remove Application Insights from updater pending otel fix

- adoptium-frontend-parent/adoptium-api-v3-frontend/pom.xml
- adoptium-frontend-parent/adoptium-api-v3-frontend/src/main/resources/application.properties
> fix swagger-ui

- .github/workflows/actions/azure-login/action.yml
- .github/workflows/actions/do-login/action.yml
- .github/workflows/actions/docker-build/action.yml
- .github/workflows/actions/kubectl-redeploy/action.yml
- .github/workflows/deploy-adoptium.yml
- .github/workflows/deploy-adoptopenjdk.yml
- deploy/Dockerfile
Secret added in https://github.com/adoptium/.eclipsefdn/pull/23
> add DigitalOcean to redeploy steps

- .github/workflows/deploy-adoptium.yml
- .github/workflows/deploy-adoptopenjdk.yml
> another fix

- .github/workflows/deploy-adoptium.yml
- .github/workflows/deploy-adoptopenjdk.yml
> fix actions path

- .github/actions/do-login/action.yml
- .github/actions/kubectl-redeploy/action.yml
> add shell to commands

- .github/workflows/deploy-adoptopenjdk.yml
> Merge prod into main

- .mvn/wrapper/maven-wrapper.properties
- adoptium-api-versions/pom.xml
- pom.xml
Not certain it's the good way to fix the Dependabot pull request about Maven, but here is my PR
> Fix a pb with Dependabot pull request (Maven)

- marketplace/adoptium-marketplace-utils/src/test/kotlin/ExtractAdoptiumReleases.kt
I think we have to add the 21 here to be extracted.
> Add 21 to version to extract

- .github/dependabot.yml
- deploy/Dockerfile
> bump deploy dockerfile to Temurin 21

- adoptium-api-versions/pom.xml
Fix the PR of depbot https://github.com/adoptium/api.adoptium.net/pull/773
> Updated-dependencies: graphql-kotlin from 7.0.1 to 7.0.2

- .mvn/wrapper/maven-wrapper.properties
- adoptium-api-versions/pom.xml
- pom.xml
This PR is to fix manually the PR https://github.com/adoptium/api.adoptium.net/pull/820
> Maven/org.apache.maven maven artifact 3.9.6

- adoptium-api-versions/pom.xml
Upgrade both io.smallrye libraries
> Upgrade both io.smallrye libraries

- CONTRIBUTING.md
Add command "How to upgrade Maven" in CONTRIBUTING.
> Add command "How to upgrade Maven" in CONTRIBUTING

- adoptium-updater-parent/adoptium-datasources-parent/adoptium-github-datasource/pom.xml
- adoptium-updater-parent/adoptium-datasources-parent/adoptium-http-client-datasource/pom.xml
Upgrade all librairies in one shot
> Upgrade all io-jsonwebtoken-jjwt-* libraries

- .github/actions/azure-login/action.yml
- .github/actions/do-login/action.yml
- .github/actions/docker-build/action.yml
- .github/workflows/ci.yml
- .github/workflows/publish.yml
- adoptium-api-versions/pom.xml
- adoptium-updater-parent/adoptium-datasources-parent/adoptium-github-datasource/pom.xml
- adoptium-updater-parent/adoptium-datasources-parent/adoptium-http-client-datasource/pom.xml
- docs/cookbook.adoc
- pom.xml
> merge main into prod

- adoptium-api-v3-persistence/src/main/kotlin/net/adoptium/api/v3/dataSources/persitence/mongo/MongoClient.kt
- deploy/run.sh
> Apply test fixes for #861

- adoptium-frontend-parent/adoptium-api-v3-frontend/src/main/kotlin/net/adoptium/api/v3/routes/info/AvailableOperatingSystemsResource.kt
- adoptium-frontend-parent/adoptium-api-v3-frontend/src/test/kotlin/net/adoptium/api/AvailableOperatingSystemsPathTest.kt
Correct two words path by using an underscore
> Correct two words path by using an underscore

- .github/workflows/codeql.yml
> add codeQL workflow

- adoptium-frontend-parent/adoptium-api-v3-frontend/src/main/kotlin/net/adoptium/api/v3/OpenApiDocs.kt
- adoptium-frontend-parent/adoptium-api-v3-frontend/src/main/kotlin/net/adoptium/api/v3/routes/info/AvailableReleasesResource.kt
- adoptium-frontend-parent/adoptium-api-v3-frontend/src/test/kotlin/net/adoptium/api/AvailableReleasesPathTest.kt
- adoptium-frontend-parent/adoptium-api-v3-frontend/src/test/kotlin/net/adoptium/api/JsonSerializationTest.kt
- docs/cookbook.adoc
Rollback to historical path from /available/releases to /available_releases
> [Available Releases] Rollback to historical path

- adoptium-frontend-parent/adoptium-api-v3-frontend/src/main/kotlin/net/adoptium/api/v3/routes/info/TypesArchitecturesResource.kt
- adoptium-frontend-parent/adoptium-api-v3-frontend/src/main/kotlin/net/adoptium/api/v3/routes/info/TypesOperatingSystemsResource.kt
- adoptium-frontend-parent/adoptium-api-v3-frontend/src/test/kotlin/net/adoptium/api/TypesArchitecturesPathTest.kt
- adoptium-frontend-parent/adoptium-api-v3-frontend/src/test/kotlin/net/adoptium/api/TypesOperatingSystemsPathTest.kt
Ajust final paths for new types (Architectures & OperatingSystems)
it's : 
- /v3/types/architectures
- /v3/types/operating_systems
> Ajust final paths for new types (Architectures & OperatingSystems)

- adoptium-api-v3-persistence/src/main/kotlin/net/adoptium/api/v3/dataSources/persitence/mongo/MongoClient.kt
> Default DISABLE_MONGO_HOST_CHECK to false

- adoptium-updater-parent/adoptium-api-v3-updater/src/main/kotlin/net/adoptium/api/v3/ReleaseIncludeFilter.kt
- adoptium-updater-parent/adoptium-api-v3-updater/src/test/kotlin/net/adoptium/api/GraphQLGitHubReleaseClientTest.kt
- adoptium-updater-parent/adoptium-datasources-parent/adoptium-github-datasource/src/main/kotlin/net/adoptium/api/v3/dataSources/github/graphql/clients/GraphQLGitHubRepositoryClient.kt
> Fix filter so date filter is applied to non-excluded vendors

- adoptium-api-v3-persistence/src/main/kotlin/net/adoptium/api/v3/dataSources/APIDataStoreImpl.kt
> Fix front end initial db update

- adoptium-updater-parent/adoptium-datasources-parent/adoptium-github-datasource/pom.xml
- adoptium-updater-parent/adoptium-datasources-parent/adoptium-http-client-datasource/pom.xml
> Bump io.jsonwebtoken:jjwt-impl from 0.12.5 to 0.12.6

- deploy/Dockerfile
> Fix ubuntu 24 Docker update

- deploy/Dockerfile
> Fix permissions in docker container

- deploy/Dockerfile
> Simplify permissions and move to 21-jammy

- adoptium-api-versions/pom.xml
- pom.xml
> Bump quarkus.version from 3.11.2 to 3.13.0

- adoptium-frontend-parent/adoptium-api-v3-frontend/pom.xml
- adoptium-updater-parent/adoptium-api-v3-updater/pom.xml
Added Quarkus Micrometer support for Prometheus
> Expose Prometheus metrics for user pods in AKS

- .github/actions/azure-login/action.yml
> Login to ACR via OIDC

- .github/actions/azure-login/action.yml
> Specify shell for Azure ACR login

- .github/actions/azure-login/action.yml
- .github/workflows/deploy-adoptium.yml
- .github/workflows/deploy-adoptopenjdk.yml
> cleanup removed secrets

- adoptium-frontend-parent/adoptium-api-v3-frontend/src/main/kotlin/net/adoptium/api/v3/CacheControlService.kt
- adoptium-frontend-parent/adoptium-api-v3-frontend/src/test/kotlin/net/adoptium/api/AssetsResourceFeatureReleasePathTest.kt
> Reduce cache control max age

- adoptium-frontend-parent/adoptium-api-v3-frontend/src/main/kotlin/net/adoptium/api/v3/CacheControlService.kt
- adoptium-frontend-parent/adoptium-api-v3-frontend/src/test/kotlin/net/adoptium/api/AssetsResourceFeatureReleasePathTest.kt
- adoptium-updater-parent/adoptium-api-v3-updater/src/main/kotlin/net/adoptium/api/v3/V3Updater.kt
- adoptium-updater-parent/adoptium-api-v3-updater/src/test/kotlin/net/adoptium/api/V3UpdaterTest.kt
> take into account the url when calculating etag

- adoptium-frontend-parent/adoptium-api-v3-frontend/src/main/kotlin/net/adoptium/api/v3/CacheControlService.kt
- adoptium-frontend-parent/adoptium-api-v3-frontend/src/test/kotlin/net/adoptium/api/AssetsResourceFeatureReleasePathTest.kt
> add new etag to filtered routes

- adoptium-api-v3-persistence/src/main/kotlin/net/adoptium/api/v3/dataSources/persitence/mongo/UpdatedInfo.kt
- adoptium-frontend-parent/adoptium-api-v3-frontend/src/main/kotlin/net/adoptium/api/v3/CacheControlService.kt
> Remove unused hexChecksum

- .github/actions/docker-build/action.yml
- .github/workflows/deploy-adoptium.yml
- .github/workflows/deploy-adoptopenjdk.yml
> Set docker build directory in action

- .github/actions/docker-build/action.yml
- .github/workflows/deploy-adoptium.yml
- .github/workflows/deploy-adoptopenjdk.yml
- deploy/mongo/Dockerfile
> Fix docker build

- .github/workflows/deploy-adoptium.yml
- .github/workflows/deploy-adoptopenjdk.yml
> Reference correct docker file

- adoptium-frontend-parent/adoptium-api-v3-frontend/src/main/kotlin/net/adoptium/api/v3/Pagination.kt
- adoptium-frontend-parent/adoptium-api-v3-frontend/src/main/kotlin/net/adoptium/api/v3/routes/AssetsResource.kt
- adoptium-frontend-parent/adoptium-api-v3-frontend/src/main/kotlin/net/adoptium/api/v3/routes/VersionResource.kt
- adoptium-frontend-parent/adoptium-api-v3-frontend/src/main/kotlin/net/adoptium/api/v3/routes/info/ReleaseListResource.kt
- adoptium-frontend-parent/adoptium-api-v3-frontend/src/main/kotlin/net/adoptium/api/v3/routes/info/ReleaseNotesResource.kt
- adoptium-frontend-parent/adoptium-api-v3-frontend/src/main/kotlin/net/adoptium/api/v3/routes/packages/BinaryResource.kt
- adoptium-frontend-parent/adoptium-api-v3-frontend/src/main/kotlin/net/adoptium/api/v3/routes/packages/ChecksumResource.kt
- adoptium-frontend-parent/adoptium-api-v3-frontend/src/main/kotlin/net/adoptium/api/v3/routes/packages/InstallerResource.kt
- adoptium-frontend-parent/adoptium-api-v3-frontend/src/main/kotlin/net/adoptium/api/v3/routes/packages/SignatureResource.kt
- adoptium-frontend-parent/adoptium-api-v3-frontend/src/main/kotlin/net/adoptium/api/v3/routes/stats/DownloadStatsResource.kt
- adoptium-frontend-parent/adoptium-api-v3-frontend/src/test/kotlin/net/adoptium/api/AssetsResourceFeatureReleasePathSortOrderTest.kt
- adoptium-frontend-parent/adoptium-api-v3-frontend/src/test/kotlin/net/adoptium/api/AssetsResourceReleaseNamePathTest.kt
- adoptium-updater-parent/adoptium-api-v3-updater/src/main/kotlin/net/adoptium/api/v3/stats/dockerstats/DockerStatsInterface.kt
- adoptium-updater-parent/adoptium-api-v3-updater/src/main/kotlin/net/adoptium/api/v3/stats/dockerstats/DockerStatsInterfaceAdoptOpenJdk.kt
- adoptium-updater-parent/adoptium-api-v3-updater/src/main/kotlin/net/adoptium/api/v3/stats/dockerstats/DockerStatsInterfaceAdoptium.kt
> Fix Schema generation for #1351

- adoptium-api-v3-persistence/src/main/kotlin/net/adoptium/api/v3/dataSources/persitence/mongo/MongoApiPersistence.kt
- adoptium-models-parent/adoptium-api-v3-models/src/main/kotlin/net/adoptium/api/v3/dataSources/models/AdoptRepos.kt
- adoptium-updater-parent/adoptium-api-v3-updater/src/main/kotlin/net/adoptium/api/v3/V3Updater.kt
- adoptium-updater-parent/adoptium-api-v3-updater/src/main/kotlin/net/adoptium/api/v3/stats/GitHubDownloadStatsCalculator.kt
- adoptium-updater-parent/adoptium-api-v3-updater/src/test/kotlin/net/adoptium/api/StatsCalculatorTest.kt
- adoptium-updater-parent/adoptium-mappers-parent/adopt-mappers/src/main/kotlin/net/adoptium/api/v3/mapping/adopt/AdoptReleaseMapper.kt
> add stats sanity check before writing to db

- adoptium-frontend-parent/adoptium-api-v3-frontend/src/main/kotlin/net/adoptium/api/v3/CacheControlService.kt
- adoptium-frontend-parent/adoptium-api-v3-frontend/src/test/kotlin/net/adoptium/api/AssetsResourceFeatureReleasePathTest.kt
> Add quotes to etags

- adoptium-frontend-parent/adoptium-api-v3-frontend/src/main/kotlin/net/adoptium/api/v3/CacheControlService.kt
- adoptium-frontend-parent/adoptium-api-v3-frontend/src/test/kotlin/net/adoptium/api/AssetsResourceFeatureReleasePathTest.kt
> Prevent duplicate etag

- deploy/mongo/Dockerfile
> Limit mongo cache to 1gb

- adoptium-frontend-parent/adoptium-api-v3-frontend/src/main/resources/application.properties
> Fix incorrect cors setting
