adoptium/api.adoptium.net

.github/workflows/build.yml, pom.xml
Updates of most of the dependabot suggestions.
Skipped the openapi generator plugin due to major version step.
Latest (4.2.*) mongo-core and kmongo versions causing test failures, need to be analysed, 4.1 versions working well.
@johnoliver 
@karianna
=> Dependency version updates

adoptopenjdk-api-v3-frontend/pom.xml, adoptopenjdk-api-v3-persistence/pom.xml, adoptopenjdk-api-v3-updater/pom.xml, pom.xml
To be able to change to latest kmongo and coroutine versions, some
cleanup in mongodb dependencies where necessary as declared versions
where incompatible.
MongoDB drivers are now only transient dependencies of kmongo to avoid
such incompatibilities in the future.
=> Update kmongo to 4.2, coroutine to 1.4 and other dependencies

adoptopenjdk-api-v3-persistence/src/main/kotlin/net/adoptopenjdk/api/v3/DownloadStatsInterface.kt
Return 36 months of monthly download tracking data rather than 6 for improved historical analysis.
=> Add env var to configure how much monthly tracking data returned

.github/workflows/build-docker.yml, marketplace/adoptium-marketplace-schema-tests/src/test/java/net/adoptium/marketplace/schema/DeserializationTest.java, marketplace/adoptium-marketplace-schema/src/main/java/net/adoptium/marketplace/schema/JvmImpl.java, marketplace/adoptium-marketplace-schema/src/main/java/net/adoptium/marketplace/schema/Project.java, marketplace/adoptium-marketplace-schema/src/main/java/net/adoptium/marketplace/schema/Release.java, marketplace/adoptium-marketplace-schema/src/main/java/net/adoptium/marketplace/schema/Vendor.java, pom.xml
- allow for OpenJ9 based JVMs in the marketplace
- add Azul to vendor list
- remove non-jck project releases
- add links for AQAvit results, and TCK statement
=> Updates to the marketplace schema

adoptium-models-parent/adoptium-api-v3-models/src/main/kotlin/net/adoptium/api/v3/config/APIConfig.kt, adoptium-models-parent/adoptium-api-v3-models/src/main/kotlin/net/adoptium/api/v3/dataSources/models/AdoptRepos.kt, adoptium-updater-parent/adoptium-api-v3-updater/pom.xml, adoptium-updater-parent/adoptium-api-v3-updater/src/main/kotlin/net/adoptium/api/v3/AdoptRepository.kt, adoptium-updater-parent/adoptium-api-v3-updater/src/main/kotlin/net/adoptium/api/v3/V3Updater.kt, adoptium-updater-parent/adoptium-api-v3-updater/src/test/kotlin/net/adoptium/api/V3UpdaterTest.kt
Since AdoptOpenJDK repositories are effectively archived, it is expensive to keep polling and update them every full update cycle. This treats them as set in stone, stops polling for updates, and simply carries forward the existing AdoptOpenJDK data.
=> Stop updating Adoptopenjdk repositories

adoptium-updater-parent/adoptium-mappers-parent/adopt-mappers/src/main/kotlin/net/adoptium/api/v3/mapping/adopt/AdoptReleaseMapper.kt
- sbom binary named as *sbom<XXX>.json
- sbom metadta named as *sbom<XXX>-metadata.json
- filter release binary if match:
- file name not end with .json
- file name contains 'sbom' but not end with '-metadata.json'
- filter assets if match_
- file name end with .json
- file name contains 'sbom' and end with '-metadata.json'
- map "asserts" with "binary"
-  non-sbom, same as before
- sbom: remove .json as suffix , compare *sbom-metadata.json with *sbom 
[see slack conversation ](https://adoptium.slack.com/archives/CFUJV9XV0/p1655808944201159)
Ref: https://github.com/adoptium/ci-jenkins-pipelines/issues/328
Ref2: https://github.com/adoptium/ci-jenkins-pipelines/pull/329
=> feat: add support for sbom and sbom metadata file_

adoptium-updater-parent/adoptium-mappers-parent/adopt-mappers/src/main/kotlin/net/adoptium/api/v3/mapping/adopt/AdoptBinaryMapper.kt
This will add in the ability to retrieve the `.sig` files used for GPG signing our releases (once I start uploading them!)
Submitting this for now so that any problems during review are resolved.
Signed-off-by: Stewart X Addison <sxa@redhat.com>
=> Add support for Temurin GPG signature retrieval

deploy/Dockerfile
Fixes test failures unable to find libcrypto
=> Fix failing docker build

.github/dependabot.yml, .github/workflows/build-marketplace.yml
=> store build-marketplace action in main to get dependabot updates

adoptium-frontend-parent/adoptium-api-v3-frontend/src/main/kotlin/net/adoptium/api/v3/routes/stats/DownloadStatsResource.kt, adoptium-frontend-parent/adoptium-api-v3-frontend/src/test/kotlin/net/adoptium/api/DownloadStatsPathTest.kt, adoptium-models-parent/adoptium-api-v3-models/src/main/kotlin/net/adoptium/api/v3/models/ReleaseType.kt
This PR is to resolve (partially) this issue https://github.com/adoptium/dash.adoptium.net/issues/385
There is some inconsistency in data returned by the API.
Two endpoints do not return same data because they do not filter values in the same way.
Filter is `            .filter { it.release_type == ReleaseType.ga }`
line 67 getTotalDownloadStats() 
:warning:  do not have the filter
and 
line 93 getTotalDownloadStatsForTag()
:heavy_check_mark:  have a filter
:arrow_right: I have added the filter to both function. Maybe I should remove the filter from the second, let me know.
=> Fix inconsistency of the data returned by the API

adoptium-frontend-parent/adoptium-api-v3-frontend/src/main/kotlin/net/adoptium/api/v3/routes/info/ReleaseListResource.kt
Is it normal that the API endpoint /release_names returns duplicated names ?
jdk-21.0.1+12 is duplicated
=> Ensure no duplicate is returned

adoptium-frontend-parent/adoptium-api-v3-frontend/src/main/kotlin/net/adoptium/api/v3/routes/packages/ChecksumResource.kt, adoptium-frontend-parent/adoptium-api-v3-frontend/src/main/kotlin/net/adoptium/api/v3/routes/packages/PackageEndpoint.kt, adoptium-frontend-parent/adoptium-api-v3-frontend/src/main/kotlin/net/adoptium/api/v3/routes/packages/SignatureResource.kt, adoptium-frontend-parent/adoptium-api-v3-frontend/src/test/kotlin/net/adoptium/api/packages/BinaryPathTest.kt, adoptium-frontend-parent/adoptium-api-v3-frontend/src/test/kotlin/net/adoptium/api/packages/ChecksumPathTest.kt, adoptium-frontend-parent/adoptium-api-v3-frontend/src/test/kotlin/net/adoptium/api/packages/InstallerPathTest.kt, adoptium-frontend-parent/adoptium-api-v3-frontend/src/test/kotlin/net/adoptium/api/packages/PackageEndpointTest.kt, adoptium-frontend-parent/adoptium-api-v3-frontend/src/test/kotlin/net/adoptium/api/packages/SignaturePathTest.kt, adoptium-updater-parent/adoptium-api-v3-updater/src/test/kotlin/net/adoptium/api/AdoptReposTestDataGenerator.kt
This PR is related to the issue #853 
I have added to new endpoints that can by used to download checksum or signature of a specific version.
=> Add endpoints for checksum and signature

docs/cookbook.adoc
Fixes #921 
As provided by the community, I have added an example PowerShell script that utilises the API to download the JDKs.
=> Documentation: Add an example of a powershell script that uses the API

adoptium-frontend-parent/adoptium-api-v3-frontend/src/main/kotlin/net/adoptium/api/v3/routes/info/AvailableArchitecturesResource.kt, adoptium-frontend-parent/adoptium-api-v3-frontend/src/main/kotlin/net/adoptium/api/v3/routes/info/AvailableOperatingSystemsResource.kt, adoptium-frontend-parent/adoptium-api-v3-frontend/src/test/kotlin/net/adoptium/api/AvailableArchitecturesPathTest.kt, adoptium-frontend-parent/adoptium-api-v3-frontend/src/test/kotlin/net/adoptium/api/AvailableOperatingSystemsPathTest.kt
Hello, 
Why not add some usefull endpoints to share more data with users.
Let's start with:
- Supported Architectures
- Support Operating Systems
What do you think?
=> Add various usefull endpoints: get supported Architectures & Operating Systems

adoptium-frontend-parent/adoptium-api-v3-frontend/src/main/kotlin/net/adoptium/api/v3/OpenApiDocs.kt, adoptium-frontend-parent/adoptium-api-v3-frontend/src/main/kotlin/net/adoptium/api/v3/routes/info/AvailableArchitecturesResource.kt, adoptium-frontend-parent/adoptium-api-v3-frontend/src/main/kotlin/net/adoptium/api/v3/routes/info/AvailableOperatingSystemsResource.kt, adoptium-frontend-parent/adoptium-api-v3-frontend/src/main/kotlin/net/adoptium/api/v3/routes/info/AvailableReleasesResource.kt, adoptium-frontend-parent/adoptium-api-v3-frontend/src/test/kotlin/net/adoptium/api/AvailableArchitecturesPathTest.kt, adoptium-frontend-parent/adoptium-api-v3-frontend/src/test/kotlin/net/adoptium/api/AvailableOperatingSystemsPathTest.kt, adoptium-frontend-parent/adoptium-api-v3-frontend/src/test/kotlin/net/adoptium/api/AvailableReleasesPathTest.kt, adoptium-frontend-parent/adoptium-api-v3-frontend/src/test/kotlin/net/adoptium/api/JsonSerializationTest.kt, docs/cookbook.adoc
Changes have been done on paths:
- MOVE /available_releases is now **/available/releases** (deprecated with a 301 redirect to the new location)
- ADD  **/available/architectures**
- ADD  **/available/operating-systems**
**Question**: Do we use /available/operating-systems or /available/operating_systems?
~~**Question 2**: Do you know how to hide an endpoint in this swagger version?~~
=> Add two new endpoints and normalize

.github/workflows/semgrep_diff.yml
As recommended by the security audit.
Adding a Github action to run the semgrep code scanner on each PR to identify any issues matching the rule set used in the Trail Of Bits audit.
=> Add semgrep code scanning on PRs

.github/dependabot.yml
now that dependabot supports wildcards (https://github.blog/changelog/2024-06-25-simplified-dependabot-yml-configuration-with-multi-directory-key-directories-and-wildcard-glob-support/)
=> updaste dependabot to use wildcards

.github/dependabot.yml
Reverts adoptium/api.adoptium.net#1079
Despite the docs saying dependabot supports wildcards it's broken our config so backing it out for now
=> Revert "updaste dependabot to use wildcards"

adoptium-api-versions/pom.xml
Manuel update for io.smallrye:smallrye-open-api-*
Replace following issues: 
#1069 
#1070
=> Bump io.smallrye:smallrye-open-api-* from 3.10.0 to 3.11.0

adoptium-api-versions/pom.xml
Manualy fix #1101 
- [ :heavy_check_mark:  ] `mvn clean install` build and test completes
=> Bump com.expediagroup:graphql-kotlin-* from 7.1.1 to 7.1.4

adoptium-api-v3-persistence/src/main/kotlin/net/adoptium/api/v3/dataSources/persitence/mongo/MongoInterface.kt, adoptium-frontend-parent/adoptium-api-v3-frontend/src/main/kotlin/net/adoptium/api/v3/Main.kt, adoptium-frontend-parent/adoptium-api-v3-frontend/src/main/kotlin/net/adoptium/api/v3/Startup.kt, adoptium-models-parent/adoptium-api-v3-models/src/main/kotlin/net/adoptium/api/v3/config/APIConfig.kt, adoptium-models-parent/adoptium-api-v3-models/src/main/kotlin/net/adoptium/api/v3/config/DeploymentType.kt, adoptium-updater-parent/adoptium-api-v3-updater/src/main/kotlin/net/adoptium/api/v3/Main.kt, deploy/run.sh
=> Catch Collection creation issues

adoptium-api-v3-persistence/src/main/kotlin/net/adoptium/api/v3/dataSources/APIDataStore.kt, adoptium-api-v3-persistence/src/main/kotlin/net/adoptium/api/v3/dataSources/APIDataStoreImpl.kt, adoptium-api-v3-persistence/src/main/kotlin/net/adoptium/api/v3/dataSources/persitence/ApiPersistence.kt, adoptium-api-v3-persistence/src/main/kotlin/net/adoptium/api/v3/dataSources/persitence/mongo/MongoApiPersistence.kt, adoptium-frontend-parent/adoptium-api-v3-frontend/src/test/kotlin/net/adoptium/api/ApiDataStoreStub.kt, adoptium-updater-parent/adoptium-api-v3-updater/src/main/kotlin/net/adoptium/api/v3/V3Updater.kt, adoptium-updater-parent/adoptium-api-v3-updater/src/test/kotlin/net/adoptium/api/V3UpdaterTest.kt, adoptium-updater-parent/adoptium-api-v3-updater/src/test/kotlin/net/adoptium/api/testDoubles/InMemoryApiPersistence.kt
Fixes #1277 
Applying this in conjunction with applying a health probe to delay the container start until the database is available
=> Apply fix to exit updater if the mongodb is not present when the container starts

adoptium-models-parent/adoptium-api-v3-models/src/main/kotlin/net/adoptium/api/v3/models/ImageType.kt, adoptium-updater-parent/adoptium-api-v3-updater/src/test/kotlin/net/adoptium/api/AdoptBinaryMapperTest.kt
See: https://github.com/adoptium/adoptium-support/issues/1271
Relevant temurin-build change is:
https://github.com/adoptium/temurin-build/pull/4157
JDK 24+ has JEP 493 enabled. For some use-cases JMODs are still required.
Allow for the API to get queried for JMODs for a specific release.
=> Add support for jmods ImageType
